spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wbs_db?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    create-schemas: true
    schemas: public
    repair-on-migrate: true
    validate-on-migrate: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ai_offshore.tools.wbs.web.model

redmine:
  url: https://benefit-one.net/extrdmn
  api-key: e1b2766512ba4f2b8098df6ecd3bb60e6b0c32c9 